### ISSUE TITLE
模型train loss不变

### ISSUE THREAD

**Issue by neowangzc** [nuster1128/RecBole-MetaRec#6]
只更改了quickstart.py，'MWUF', 'ml-100k-CTR'，发现每个epoch都没有变化
27 Nov 14:49    INFO  epoch 0 training [time: 24.48s, train loss: 1.3043]
27 Nov 14:49    INFO  epoch 0 evaluating [time: 0.07s, valid_score: 0.428900]
27 Nov 14:49    INFO  valid result: 
auc : 0.4289
27 Nov 14:49    INFO  Saving current: saved\MWUF-Nov-27-2022_14-49-09.pth
27 Nov 14:49    INFO  epoch 1 training [time: 1.82s, train loss: 1.3043]
27 Nov 14:49    INFO  epoch 1 evaluating [time: 0.07s, valid_score: 0.428900]
27 Nov 14:49    INFO  valid result: 
auc : 0.4289
27 Nov 14:49    INFO  Saving current: saved\MWUF-Nov-27-2022_14-49-09.pth
27 Nov 14:49    INFO  epoch 2 training [time: 1.96s, train loss: 1.3043]
27 Nov 14:49    INFO  epoch 2 evaluating [time: 0.07s, valid_score: 0.428900]
27 Nov 14:49    INFO  valid result: 
auc : 0.4289
27 Nov 14:49    INFO  Saving current: saved\MWUF-Nov-27-2022_14-49-09.pth
27 Nov 14:49    INFO  epoch 3 training [time: 1.81s, train loss: 1.3043]
27 Nov 14:49    INFO  epoch 3 evaluating [time: 0.07s, valid_score: 0.428900]
27 Nov 14:49    INFO  valid result: 
auc : 0.4289
27 Nov 14:49    INFO  Saving current: saved\MWUF-Nov-27-2022_14-49-09.pth
27 Nov 14:49    INFO  epoch 4 training [time: 1.82s, train loss: 1.3043]
27 Nov 14:49    INFO  epoch 4 evaluating [time: 0.06s, valid_score: 0.428900]
27 Nov 14:49    INFO  valid result: 
auc : 0.4289
27 Nov 14:49    INFO  Saving current: saved\MWUF-Nov-27-2022_14-49-09.pth
27 Nov 14:49    INFO  epoch 5 training [time: 1.81s, train loss: 1.3043]
27 Nov 14:49    INFO  epoch 5 evaluating [time: 0.07s, valid_score: 0.428900]
27 Nov 14:49    INFO  valid result: 
auc : 0.4289

**Comment by nuster1128** [comment]
Thanks for your issue. Acutuall in the original paper of MWUF, MovieLens-100K is not included in the experiment and we have tried our best to implement the model and tune the hyper-parameters. However, many factors may contribute to this phenomenon. You can change some hyper-parameters or hyper-layers that we have fixed and have another try.
